@startuml

title Sequence LOGIN

actor Utilisateur
participant "LoginController" as LC
participant "NetworkClient" as NC
participant "Socket TCP" as S
participant "Serveur C" as SC

Utilisateur -> LC : tape IP / Port / Pseudo
Utilisateur -> LC : clic Se connecter
LC -> LC : validation des champs
LC -> NC : connect(ip, port, username)
NC -> S : new Socket(ip, port)
S -> SC : connexion TCP
NC -> NC : demarre thread listenLoop
NC -> S : send LOGIN
S -> SC : {"action":"LOGIN"}

alt identifiants valides
    SC -> S : {"status":"OK","action":"LOGIN_SUCCESS"}
    S -> NC : ligne JSON
    NC -> LC : callback
    LC -> Utilisateur : Bienvenue usman
else pseudo deja pris
    SC -> S : {"status":"ERROR","code":"USERNAME_TAKEN"}
    S -> NC : ligne JSON
    NC -> LC : callback
    LC -> Utilisateur : Message d'erreur
end
@enduml
