@startuml

title Sequence CREATE_CARD

actor Utilisateur
participant "CardController" as CC
participant "NetworkClient" as NC
participant "Serveur C" as SC

Utilisateur -> CC : remplit formulaire
Utilisateur -> CC : clic Creer
CC -> CC : validation
CC -> NC : send CREATE_CARD
NC -> SC : {"action":"CREATE_CARD"}

alt donnees valides
    SC -> SC : genere card_id
    SC -> SC : mine un bloc
    SC -> NC : {"status":"OK","action":"CARD_CREATED"}
    NC -> CC : callback
    CC -> Utilisateur : affiche nouvelle carte
else donnees invalides
    SC -> NC : {"status":"ERROR","code":"INVALID_DATA"}
    NC -> CC : callback
    CC -> Utilisateur : Message d'erreur
end
@enduml
