@startuml

title Sequence BATTLE

actor "Utilisateur A" as U1
participant "BattleController" as BC
participant "NetworkClient" as NC
participant "Serveur C" as SC
participant "Autres clients" as AC

U1 -> BC : clic Lancer battle
BC -> NC : send START_BATTLE
NC -> SC : {"action":"START_BATTLE"}

SC -> SC : verifie cartes ACTIVE
SC -> SC : verifie meme paradigm
SC -> SC : verifie VA >= 5
SC -> SC : mine un bloc

alt battle acceptee
    SC -> NC : {"status":"OK","action":"BATTLE_STARTED"}
    SC -> AC : {"status":"NOTIFY","action":"NEW_BATTLE"}
    NC -> BC : callback
    BC -> U1 : affiche battle
else cartes non comparables
    SC -> NC : {"status":"ERROR","code":"CARDS_NOT_COMPATIBLE"}
    NC -> BC : callback
    BC -> U1 : Message d'erreur
end
@enduml
