@startsalt
{+
  Connexion au serveur
  .
  SAE BUT2 S3 - Plateforme de recommandations
  .
  ---
  Adresse IP : | "127.0.0.1        "
  Port       : | "8080             "
  Pseudo     : | "usman            "
  ---
  { [Se connecter] | [Quitter] }
  .
  "Serveur injoignable"
}
@endsalt
