@startsalt
{+
  Client de recommandations
  .
  {/ <b>Cartes | Mes cartes | Recommandations | Battles | Profil }
  .
  {+
    { [ + Creer une carte ] | Recherche : | "              " | [Q] }
    .
    {
      {+
        [Logo]
        Python
        Multi-paradigme
        "15"
        [Recommander]
        [Battle]
      }
      | {+
        [Logo]
        Java
        Oriente objet
        "11"
        [Recommander]
        [Battle]
      }
    }
  }
  .
  {/ Connecte a 127.0.0.1:8080 | Utilisateur : usman }
}
@endsalt
