@startsalt
{+
  { [ + Lancer une battle ] }
  .
  {+
    Battle #b_001  (En cours)
    .
    {+
      Python
      "15"
      [Voter]
    }
    | VS |
    {+
      Java
      "11"
      [Voter]
    }
    .
    Temps restant : 00:45
  }
  .
  {+
    Battle #b_002  (Terminee)
    Gagnant : Python (c_001)
    Perdant : Java (c_002)
    Transfert : 5 VA
  }
}
@endsalt
