@startuml

title Sequence LOGIN - Client JavaFX et Serveur C

actor Utilisateur
participant "LoginController" as LC
participant "NetworkClient" as NC
participant "Socket TCP" as S
participant "Serveur C" as SC

Utilisateur -> LC : tape IP / Port / Pseudo
Utilisateur -> LC : clic Se connecter

LC -> LC : validation des champs
LC -> NC : connect(ip, port, username)

NC -> S : new Socket(ip, port)
S -> SC : connexion TCP

NC -> NC : demarre thread listenLoop

NC -> S : send LOGIN
S -> SC : {"action":"LOGIN","payload":{"username":"usman"}}

SC -> SC : verifie pseudo
SC -> SC : reconstitue le contexte

alt identifiants valides
    SC -> S : {"status":"OK","action":"LOGIN_SUCCESS","data":{...}}
    S -> NC : ligne JSON
    NC -> NC : gson.fromJson
    NC -> LC : callback
    LC -> LC : Platform.runLater
    LC -> Utilisateur : Bienvenue usman

    SC -> S : {"status":"OK","action":"CONTEXT_RESTORED","data":{...}}
    S -> NC : ligne JSON
    NC -> LC : callback
    LC -> Utilisateur : Affichage fenetre principale

else pseudo deja pris
    SC -> S : {"status":"ERROR","code":"USERNAME_TAKEN"}
    S -> NC : ligne JSON
    NC -> LC : callback
    LC -> Utilisateur : Message d'erreur
end

@enduml
