@startuml

title Sequence RECOMMEND - Recommander une carte

actor Utilisateur
participant "CardController" as CC
participant "NetworkClient" as NC
participant "Socket TCP" as S
participant "Serveur C" as SC
participant "Autres clients" as AC

Utilisateur -> CC : clic Recommander
CC -> NC : send RECOMMEND
NC -> S : envoi JSON
S -> SC : {"action":"RECOMMEND","payload":{"cardId":"c_001"}}

SC -> SC : verifie carte ACTIVE
SC -> SC : verifie pas deja recommandee
SC -> SC : value = value + 1
SC -> SC : mine un bloc SHA-256

alt succes
    SC -> S : {"status":"OK","action":"RECOMMENDATION_ADDED","data":{"newValue":13}}
    S -> NC : ligne JSON
    NC -> CC : callback
    CC -> CC : Platform.runLater
    CC -> Utilisateur : Valeur mise a jour

    SC -> AC : {"status":"NOTIFY","action":"CARD_UPDATED","data":{"cardId":"c_001","value":13}}
    AC -> AC : MAJ affichage

else carte inactive
    SC -> S : {"status":"ERROR","code":"CARD_NOT_ACTIVE"}
    S -> NC : ligne JSON
    NC -> CC : callback
    CC -> Utilisateur : Message d'erreur
end

@enduml
